# Generated by Django 5.1.6 on 2025-02-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qr_code', models.CharField(max_length=200, unique=True)),
                ('model_file', models.FileField(upload_to='models3d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
