# Generated by Django 5.1.6 on 2025-02-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models3d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='qr_code_image',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='qr_code',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
