# Generated by Django 5.1.6 on 2025-02-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models3d', '0002_model3d_qr_code_image_alter_model3d_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='firebase_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
