# Generated by Django 5.1.6 on 2025-02-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models3d', '0003_model3d_firebase_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model3d',
            name='firebase_url',
        ),
    ]
