# Generated by Django 5.1.6 on 2025-03-06 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models3d', '0004_remove_model3d_firebase_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='scan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models3d.model3d')),
            ],
        ),
    ]
