# Generated by Django 5.1.6 on 2025-06-17 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models3d', '0005_model3d_scan_count_scan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='type',
            field=models.CharField(choices=[('static', 'Statique'), ('animated', 'Animé'), ('video', 'Vidéo')], default='static', max_length=20),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='scan_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('3D', 'Modèle 3D'), ('Video', 'Vidéo')], max_length=10)),
                ('file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
