# Generated by Django 5.1.6 on 2025-06-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models3d', '0006_model3d_type_alter_model3d_scan_count_mediamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='mind_file',
            field=models.FileField(blank=True, null=True, upload_to='mind_targets/'),
        ),
    ]
